### ISSUE TITLE
New users get an error when creating the first snippet

### ISSUE THREAD

**Issue by nezhar** [snypy/snypy-frontend#1035]
New users will receive an error due to the fact that the store tries to map some properties to the active snippet, which in case of a new user does not exist:

```
main.c501ba477e917abd.js:1 ERROR TypeError: Cannot read properties of undefined (reading 'pk')
    at main.c501ba477e917abd.js:1:1864561
    at Array.find (<anonymous>)
    at Object.next (main.c501ba477e917abd.js:1:1864535)
    at fe.value (main.c501ba477e917abd.js:1:2189444)
    at Ve.value (main.c501ba477e917abd.js:1:2188926)
    at Ve.value (main.c501ba477e917abd.js:1:2188475)
    at main.c501ba477e917abd.js:1:616140
    at _.value (polyfills.f8f4fc74a204d933.js:1:10109)
    at Object.onInvoke (main.c501ba477e917abd.js:1:2450985)
    at _.value (polyfills.f8f4fc74a204d933.js:1:10049)
```

**Comment by nezhar** [comment]
It seems that every new snippet is affected by this issue until the filter is reloaded.
